### ISSUE TITLE
Add React components for `Value`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra_dapp#20]
There are a number of different places in the existing code that render a `Value` to a human-readable string; this code should be extracted into a common component.

To render a `Value`, the value component should take an optional `DenomMetadata`. If the metadata is present, it should format a nice human-readable string with the correct denom exponent. If the metadata is missing, it should render the bare value with the raw asset bech32 string `passet1...`. 

In the future, we should change the `ValueView` to contain a `DenomMetadata` rather than just a bare denom string (https://github.com/penumbra-zone/penumbra/issues/2783), so that the `ValueView` can be rendered in a self-contained way but this hasn't happened yet.  When that happens, we could have a value view component that uses the supplied denom metadata.

**Comment by Valentine1898** [comment]
fixed here 
https://github.com/penumbra-zone/penumbra_dapp/commit/a60e02ed8dafad01a3adb49ffa21f7cc4c277523#diff-faaaf50edcff93035d4906becb3d3579aa3274c3426e26c9c61b7525a07b5063R22
